version: '3'

services:
  flutter_web:
    image: fabbo/balhom-web-flutter:latest
    container_name: balhom-web-flutter
    ports:
      - "9000:80"
      #- "9001:443" # Uncomment for HTTPS
    #volumes:
      #- ./certs:/etc/nginx/ssl:ro # Uncomment for HTTPS
    environment:
      - USE_HTTPS=false # Set to true to enable HTTPS
      - BALHOM_API_URL=http://127.0.0.1:8000
      - CURRENCY_CONVERSION_API_URL=http://127.0.0.1:18070
      - CURRENCY_CONVERSION_API_KEY=secret
    restart: unless-stopped
    networks:
      - balhom_web_net

networks:
  balhom_web_net:
