apiVersion: apps/v1
kind: Deployment
metadata:
  name: balhom-web-flutter-deployment
  namespace: balhom
spec:
  selector:
    matchLabels:
      app: balhom-web-flutter
  replicas: 1
  template:
    metadata:
      labels:
        app: balhom-web-flutter
    spec:
      containers:
        - name: balhom-web-flutter
          image: fabbo/balhom-web:flutter-2.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: BALHOM_API_URL
              valueFrom:
                configMapKeyRef:
                  name: balhom-web-flutter-configmap
                  key: balhom-api-url
            - name: CURRENCY_CONVERSION_API_URL
              valueFrom:
                configMapKeyRef:
                  name: balhom-web-flutter-configmap
                  key: currency-conversion-api-url
            - name: CURRENCY_CONVERSION_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: balhom-web-flutter-configmap
                  key: currency-conversion-api-key
