apiVersion: v1
kind: Service
metadata:
  name: balhom-web-flutter-service
  namespace: balhom
  labels:
    app: balhom-web-flutter
spec:
  selector:
    app: balhom-web-flutter
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32070
