name: Nginx Web Upload to Docker Hub and Create Tag

on:
  push:
    branches:
      - main

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check build Docker Image
        run: |
          export APP_VERSION=$(grep -m 1 version flutter/pubspec.yaml | tr -s ' ' | cut -d' ' -f2 | cut -d'+' -f1 | tr -d '\n' | tr -d '\r')
          export MAJOR_VERSION=$(echo "${APP_VERSION}" | cut -d. -f1,2)
          echo "Using version ${APP_VERSION}"
          # Tag variables
          DOCKER_REPO="${DOCKER_USERNAME}/${DOCKER_REPO_NAME}"
          APP_VERSION_TAG="${DOCKER_REPO}:${APP_VERSION}"
          MAJOR_VERSION_TAG="${DOCKER_REPO}:${MAJOR_VERSION}"
          FLUTTER_VERSION_TAG="${DOCKER_REPO}:flutter-${APP_VERSION}"
          FLUTTER_TAG="${DOCKER_REPO}:flutter"
          LATEST_TAG="${DOCKER_REPO}:latest"
          # Image build
          docker build . -t ${MAJOR_VERSION_TAG}
          # Image tag
          docker tag ${MAJOR_VERSION_TAG} ${FLUTTER_VERSION_TAG}
          docker tag ${MAJOR_VERSION_TAG} ${FLUTTER_TAG}
          docker tag ${MAJOR_VERSION_TAG} ${LATEST_TAG}
          # Image push
          docker push ${MAJOR_VERSION_TAG}
          docker push ${FLUTTER_VERSION_TAG}
          docker push ${FLUTTER_TAG}
          docker push ${LATEST_TAG}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
